import './globals.css'
import Authpovider from './context/Authpovider'



export const metadata = {
  title: 'OpenInAppAssignment',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Authpovider>
      <body className='main'>{children}</body>
    </Authpovider>

    </html>
    
  )
}
